name: MicrosoftAppinspector
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  semgrep:
    runs-on: ubuntu-latest
    name: Check
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/ApplicationInspector-Action@v1
      - uses: actions/upload-artifact@v2
        with:
            name: AppInspectorResults
            path: AppInspectorResults.json
