name: MicrosoftAppinspector
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  semgrep:
    runs-on: windows-latest
    name: Check
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/ApplicationInspector-Action@v1
        with:
          arguments: -t
