name: Semgrep-All
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  semgrep:
    runs-on: ubuntu-latest
    name: Check
    continue-on-error: true
    strategy:
      matrix:
        # 'r/all', 'p/dockerfile', 'p/react'
        rulesets: 
          - p/nodejsscan
          - p/clientside-js
          - p/daghan.all js
          - p/danielcuthbert.quickjs
          - p/dduarte.test-js-pack
          - p/hazanasec.jwt-security-audit
          - p/hazanasec.generic_possible_xss
          - p/hazanasec.non-prepared-sql-statements
          - p/hazanasec.possible_hardcoded_secrets
          - p/minusworld.express-xss
          - p/reeyaa.nodejs-findsecbugs
          - p/tkisason.javascript-kitchensink
          - p/tkisason.js-all-test
    steps:
      - uses: actions/checkout@v1
      - name: Semgrep
        id: semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: ${{ matrix.rulesets }}
          generateSarif: "1"
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
         sarif_file: semgrep.sarif
        if: always()
